"""
Subdomain Hunt 201
Веб-сервер, который отвечает по-разному в зависимости от Host-заголовка.
Большинство сабдоменов возвращают стандартные сервисные страницы,
один — секретный — содержит флаг.
"""
import os
from flask import Flask, request, render_template_string

app = Flask(__name__)
FLAG = os.environ.get("FLAG", "flag{subd0m41n_hunt1ng_1s_4w3s0m3}")
DOMAIN = "megacorp.local"

# Список сабдоменов: 500 разных, плюс один секретный
SECRET_SUBDOMAIN = "vault-47"

SUBDOMAINS = [
    "www", "mail", "ftp", "ns1", "ns2", "dns", "admin", "api", "dev", "test",
    "staging", "prod", "beta", "alpha", "demo", "shop", "store", "blog", "news",
    "support", "help", "docs", "wiki", "forum", "chat", "crm", "erp", "hr", "pay",
    "billing", "account", "auth", "sso", "login", "register", "portal", "intranet",
    "remote", "vpn", "git", "ci", "cd", "jenkins", "gitlab", "github", "docker",
    "kube", "k8s", "prometheus", "grafana", "logs", "monitor", "status", "health",
    "metrics", "backup", "db", "db1", "db2", "cache", "redis", "mq", "rabbitmq",
    "kafka", "elastic", "search", "solr", "cdn", "static", "assets", "media",
    "images", "video", "stream", "live", "events", "calendar", "meet", "office",
    "teams", "share", "drive", "files", "upload", "download", "transfer", "sync",
    "update", "upgrade", "patch", "security", "siem", "soc", "ids", "ips", "waf",
    "firewall", "gateway", "proxy", "lb", "loadbalancer", "router", "switch",
    "core", "edge", "origin", "cname", "mx", "txt", "spf", "dkim", "dmarc",
    "smtp", "pop", "imap", "webmail", "exchange", "outlook", "lync", "skype",
    "zoom", "slack", "discord", "telegram", "whatsapp", "signal", "jira",
    "confluence", "trello", "asana", "notion", "monday", "zendesk", "freshdesk",
    "salesforce", "hubspot", "marketo", "mailchimp", "sendgrid", "twilio",
    "stripe", "paypal", "braintree", "adyen", "checkout", "invoice", "quote",
    "contract", "legal", "compliance", "gdpr", "privacy", "terms", "policy",
    "about", "contact", "careers", "jobs", "team", "press", "investors",
    "partners", "affiliates", "reseller", "marketplace", "integrations",
    "webhooks", "oauth", "oidc", "saml", "ldap", "ad", "active", "directory",
    "cert", "pki", "ca", "vault", "secrets", "kms", "hsm", "tokens", "keys",
    "crypto", "wallet", "blockchain", "nft", "defi", "trading", "exchange-rate",
    "api-v1", "api-v2", "api-v3", "graphql", "rest", "soap", "rpc", "grpc",
    "websocket", "socket", "realtime", "push", "pubsub", "queue", "worker",
    "scheduler", "cron", "batch", "etl", "data", "analytics", "bi", "warehouse",
    "datalake", "lakehouse", "ml", "ai", "model", "training", "inference",
    "predictions", "recommendations", "nlp", "vision", "speech", "tts", "asr",
    "bot", "agent", "assistant", "copilot", "automation", "workflow", "rpa",
    "scraper", "crawler", "indexer", "feed", "rss", "atom", "sitemap", "robots",
    "ads", "adserver", "tracking", "pixel", "tag", "analytics-tag", "gtm",
    "survey", "feedback", "reviews", "ratings", "testimonials", "cases",
    "studies", "whitepaper", "resources", "webinars", "events-calendar",
    "newsroom", "media-kit", "brand", "design", "styleguide", "ui", "ux",
    "components", "storybook", "playground", "sandbox", "labs", "research",
    "experiments", "a-b", "feature", "flags", "toggle", "config", "settings",
    "preferences", "notifications", "alerts", "incidents", "oncall", "pagerduty",
    "opsgenie", "victorops", "datadog", "newrelic", "splunk", "elk", "kibana",
    "logstash", "beats", "fluentd", "promtail", "loki", "jaeger", "zipkin",
    "tempo", "thanos", "cortex", "mimir", " victoriametrics", "clickhouse",
    "influxdb", "timescaledb", "postgresql", "mysql", "mariadb", "mongodb",
    "cassandra", "cockroach", "neo4j", "orientdb", "arangodb", "couchbase",
    "dynamodb", "firestore", "cosmos", "azure", "aws", "gcp", "cloud", "onprem",
    "legacy", "archive", "history", "old", "v1", "v2", "v3", "v4", "v5",
    "alpha-2", "beta-2", "gamma", "delta", "epsilon", "zeta", "eta", "theta",
    "iota", "kappa", "lambda", "mu", "nu", "xi", "omicron", "pi", "rho", "sigma",
    "tau", "upsilon", "phi", "chi", "psi", "omega", "aquila", "cygnus", "draco",
    "orion", "pegasus", "phoenix", "centaurus", "hydra", "leo", "virgo", "libra",
    "scorpio", "sagittarius", "capricorn", "aquarius", "pisces", "aries", "taurus",
    "gemini", "cancer", "atlantis", "olympus", "valhalla", "shangrila", "eden",
    "narnia", "gotham", "metropolis", "smallville", "starling", "nightwing",
    "batcave", "fortress", "wakanda", "asgard", "shield", "stark", "wayne",
    "lexcorp", "oscorp", "cyberdyne", "skynet", "tyrell", "weyland", "yutani",
    "massive", "array", "cluster", "node", "pod", "container", "vm", "hypervisor",
    "sandbox-1", "sandbox-2", "sandbox-3", "dev-1", "dev-2", "dev-3",
    "test-1", "test-2", "test-3", "qa-1", "qa-2", "qa-3", "preprod", "release",
    "canary", "blue", "green", "dark", "feature-x", "feature-y", "feature-z",
    "experiment-1", "experiment-2", "pilot", "trial", "preview", "early",
    "access", "invite", "join", "waitlist", "newsletter", "subscribe", "unsubscribe",
    "preferences-mail", "alerts-mail", "notify", "digest", "summary", "report",
    "weekly", "monthly", "quarterly", "annual", "yearly", "daily", "hourly",
    "real-time", "live-data", "feed-data", "stream-data", "batch-data", "etl-data",
    "pipeline", "airflow", "dagster", "prefect", "luigi", "nifi", "streamsets",
    "kafka-connect", "debezium", "flink", "spark", "storm", "samza", "pulsar",
    "heron", "druid", "pinot", "superset", "metabase", "looker", "tableau",
    "powerbi", "redash", "mode", "periscope", "sisense", "domo", "qlik",
    "thoughtspot", "tibco", "microstrategy", "sas", "spss", "stata", "matlab",
    "jupyter", "notebook", "lab", "hub", "binder", "colab", "deepnote", "hex",
    "observable", "code", "ide", "vscode", "vim", "emacs", "nano", "terminal",
    "shell", "bash", "zsh", "fish", "powershell", "cmd", "cli", "console",
    "api-docs", "developer", "platform", "sdk", "libraries", "tools", "toolbox",
    "workbench", "studio", "workshop", "academy", "university", "learning",
    "training-portal", "certification", "exams", "assessment", "evaluation",
    "survey-tool", "poll", "quiz", "form", "builder", "template", "assets-cdn",
    "font", "icons", "illustrations", "photos", "stock", "gallery", "portfolio",
    "showcase", "demo-app", "sample", "example", "tutorials", "guides", "howto",
    "faq", "kb", "knowledge-base", "help-center", "community", "discussions",
    "answers", "questions", "stack", "overflow", "ask", "expert", "consulting",
    "services", "solutions", "industries", "enterprise", "smb", "startup",
    "nonprofit", "government", "education", "healthcare", "finance", "fintech",
    "insurtech", "proptech", "edtech", "medtech", "biotech", "legaltech",
    "regtech", "agtech", "cleantech", "energy", "utilities", "telecom",
    "transportation", "logistics", "supply-chain", "manufacturing", "retail",
    "ecommerce", "marketplace-b2b", "marketplace-b2c", "auction", "classifieds",
    "directory", "listings", "reviews-site", "rating-site", "comparison",
    "price", "deal", "coupon", "promo", "discount", "loyalty", "rewards",
    "membership", "subscription", "billing-portal", "payment-portal",
    "invoice-portal", "quote-portal", "tax", "vat", "gst", "accounting",
    "bookkeeping", "payroll", "expenses", "budget", "forecast", "planning",
    "erp-finance", "erp-hr", "erp-sales", "erp-crm", "scm", "wms", "tms",
    "oms", "pim", "dam", "mdm", "plm", "qms", "ehs", "esg", "csr", "dei",
    "wellness", "benefits", "recruitment", "ats", "onboarding", "offboarding",
    "performance", "learning-lms", "compliance-training", "policy-portal",
    "ethics", "whistleblower", "risk", "audit", "internal-audit", "external-audit",
    "controls", "sox", "pci", "hipaa", "soc2", "iso27001", "iso27017", "iso27018",
    "gdpr-portal", "ccpa", "lgpd", "pdpa", "pia", "dpia", "consent", "rights",
    "dsr", "data-subject", "deletion", "retention", "backup-portal", "dr",
    "bc", "continuity", "disaster-recovery", "incident-response", "threat",
    "vulnerability", "pentest", "redteam", "blueteam", "purpleteam", "ctf",
    "bugbounty", "responsible-disclosure", "security-awareness", "phishing",
    "training-security", "simulation", "tabletop", "exercise", "war-game",
    "osint", "intelligence", "threat-intel", "ioc", "malware", "sandbox-malware",
    "analysis", "reverse", "forensics", "dfir", "ir", "investigation", "case",
    "ticketing", "itsm", "cmdb", "discovery", "mapping", "inventory", "cmms",
    "fleet", "iot", "device", "sensor", "gateway-iot", "edge-iot", "cloud-iot",
    "scada", "ics", "ot", "plc", "hmi", "dcs", "m2m", "telemetry", "remote-mon",
    "dashboard-iot", "alerts-iot", "rules-iot", "automation-iot", "digital-twin",
    "simulation-digital", "visualization", "3d", "ar", "vr", "xr", "metaverse",
    "nft-marketplace", "dao", "smart-contract", "oracle-blockchain", "chainlink",
    "the-graph", "ipfs", "filecoin", "storj", "sia", "arweave", "bittorrent",
    "webtorrent", "dat", "ssb", "activitypub", "mastodon", "matrix", "xmpp",
    "irc", "zulip", "rocket", "mattermost", "keybase", "signal-portal",
    "wire", "wickr", "threema", "session", "status-im", "brave", "tor",
    "onion", "i2p", "freenet", "zeronet", "ipns", "ens", "unstoppable",
    "handshake", "namecoin", "peercoin", "primecoin", "dogecoin", "litecoin",
    "bitcoin", "monero", "zcash", "dash", "verge", "navcoin", "pivx", "komodo",
    "ark", "nano", "iota", "tron", "eos", "stellar", "ripple", "cardano",
    "solana", "avalanche", "polkadot", "kusama", "cosmos-sdk", "tendermint",
    "near", "algorand", "tezos", "qtum", "neo", "icon", "vechain", "theta",
    "filecoin-docs", "chainlink-docs", "ethereum", "goerli", "sepolia",
    "holesky", "mumbai", "fuji", "bsc", "polygon", "arbitrum", "optimism",
    "base", "zksync", "starknet", "loopring", "immutable", "gmx", "dydx",
    "uniswap", "sushiswap", "pancakeswap", "curve", "aave", "compound",
    "makerdao", "lido", "rocketpool", "frax", "synthetix", "yearn",
    "convex", "balancer", "1inch", "paraswap", "cowswap", "matcha", "kyber",
    "bancor", "saddle", "synapse", "hop", "across", "stargate", "layerzero",
    "axelar", "wormhole", "portal-bridge", "multichain", "celer", "cbridge",
    "allbridge", "ren", "threshold", "tbtc", "wbtc", "cbbtc", "tether",
    "usdc", "busd", "dai", "frax-usd", "trueusd", "usdp", "gemini", "paxos",
    "circle", "centre", "issuer", "stablecoin", "custody", "prime-broker",
    "prime-trust", "bitgo", "fireblocks", "copper", "metaco", "ledger",
    "trezor", "safe", "gnosis-safe", "multisig", "wallet-connect", "rainbow",
    "phantom", "solflare", "metamask", "coinbase-wallet", "trust-wallet",
    "argent", "brave-wallet", "opera-wallet", "status-wallet", "zengo",
    " Exodus", "atomic", "jaxx", "mycelium", "electrum", "wasabi", "samourai",
    "sparrow", "bluewallet", "muun", "breez", "phoenix", "walletofsatoshi",
    "strike", "cashapp", "venmo", "paypal-me", "wise", "revolut", "n26",
    "monzo", "starling", "chime", "varo", "sofi", "robinhood", "webull",
    "e-trade", "fidelity", "schwab", "tdameritrade", "merrill", "wellsfargo",
    "chase", "bankofamerica", "citi", "capitalone", "amex", "discover",
    "visa", "mastercard", "maestro", "unionpay", "jcb", "diners", "club",
    "carte-bleue", "girocard", "ec-card", "bancontact", "ideal", "sofort",
    "giropay", "eps", " przelewy24", "trustly", "zimpler", "swish", "vipps",
    "mobilepay", "payconiq", "blik", "payu", "razorpay", "paytm", "phonepe",
    "googlepay", "applepay", "samsungpay", "amazonpay", "shopifypay", "stripe-uk",
    "checkout-uk", "adyen-uk", "worldpay", "fiserv", "firstdata", "global-payments",
    "elavon", "tsys", "nexi", "wirecard", "paysafe", "skrill", "neteller",
    "ecoPayz", "muchbetter", "astropay", "webmoney", "qiwi", "yoomoney",
    "tinkoff", "sberbank", "alfabank", "vtb", "raiffeisen", "unicredit",
    "ing", "deutschebank", "commerzbank", "barclays", "hsbc", "lloyds",
    "natwest", "santander", "bbva", "bnpparibas", "socgen", "credit-agricole",
    "ubs", "credit-suisse", "julius-baer", "pictet", "lombard-odier", "mirabaud",
    "edmond-de-rothschild", "efg", "banque-privee", "private-banking", "wealth",
    "asset-management", "pension", "fund", "hedge-fund", "private-equity",
    "venture-capital", "seed", "series-a", "series-b", "series-c", "ipo",
    "spac", "ma", "due-diligence", "data-room", "deal-flow", "pipeline-cr",
    "crm-deals", "salesloft", "outreach", "apollo", "zoominfo", "lusha",
    "cognism", "seamless", "leadIQ", "leadfeeder", "clearbit", "6sense",
    "demandbase", "terminus", "engagio", "bombora", "g2", "capterra",
    "trustpilot", "g2-crowd", "software-advice", "getapp", "saasworthy",
    "crozdesk", "fit-small-business", "pcmag", "techradar", "cnet", "zdnet",
    "theverge", "wired", "techcrunch", "venturebeat", "recode", "axios",
    "bloomberg", "reuters", "ft", "wsj", "nyt", "wapo", "guardian", "bbc",
    "cnn", "fox", "cnbc", "msnbc", "aljazeera", "rt", "france24", "dw",
    "afp", "ap", "upi", "reuters-insider", "marketwatch", "seekingalpha",
    "morningstar", "motley-fool", "barrons", "economist", "harvard-business",
    "mit-tech-review", "nature", "science", "ieee", "acm", "springer",
    "elsevier", "wiley", "taylor-francis", "sage", "oxford", "cambridge",
    "jstor", "arxiv", "pubmed", "google-scholar", "semantic-scholar",
    "dblp", "researchgate", "academia", "mendeley", "zotero", "endnote",
    "refworks", "citavi", "papers", "readcube", "colwiz", "overleaf",
    "sharelatex", "authorea", "figshare", "dryad", "zenodo", "osf",
    "protocols", "biorxiv", "medrxiv", "chemrxiv", "preprints",
    "hypothesis", "perusall", "cocalc", "sagemath", "wolfram", "mathematica",
    "maple", "mathworks", "ansys", "comsol", "abaqus", "solidworks",
    "autocad", "revit", "sketchup", "3dsmax", "maya", "blender", "cinema4d",
    "houdini", "nuke", "after-effects", "premiere", "photoshop", "illustrator",
    "indesign", "lightroom", "xd", "figma", "sketch", "invision", "framer",
    "principle", "proto", "marvel", "balsamiq", "axure", "mockplus",
    "origami", "pixate", "flinto", "craft", "lottie", "rive", "krita",
    "gimp", "inkscape", "scribus", "darktable", "rawtherapee", "lightzone",
    "digiKam", "shotwell", "f-spot", "geeqie", "eog", "feh", "nsxiv",
    "sxiv", "mirage", "ristretto", "viewnior", "gthumb", "phototonic",
    "nomacs", "imageglass", "irfanview", "xnview", "faststone", "xee",
    "preview", "quicklook", "seer", "glance", "wexond", "beaker",
    "min", "brave-dev", "chromium", "chrome", "firefox", "safari", "edge",
    "opera-dev", "vivaldi", "waterfox", "pale-moon", "basilisk", "tor-browser",
    "midori", "epiphany", "falkon", "qutebrowser", "surf", "luakit",
    "dillo", "links", "lynx", "w3m", "elinks", "netrik", "amfora",
    "bombadillo", "gemini", "gopher", "finger", "whois", "rdap", "bgp",
    "peeringdb", "he-net", "hurricane-electric", "dnscheck", "intodns",
    "dnsstuff", "mxtoolbox", "dmarcian", "agari", "proofpoint", "mimecast",
    "barracuda", "sophos", "forcepoint", "mcafee", "symantec", "trendmicro",
    "kaspersky", "bitdefender", "eset", "avast", "avg", "norton", "avira",
    "f-secure", "g-data", "panda", "drweb", "comodo", "zonealarm",
    "malwarebytes", "hitmanpro", "emsisoft", "webroot", "crowdstrike",
    "sentinelone", "carbonblack", "cylance", "tanium", "fireeye", "mandiant",
    "paloalto", "checkpoint", "fortinet", "juniper", "sonicwall", "watchguard",
    "sophos-firewall", "untangle", "pfsense", "opnsense", "ipfire", "smoothwall",
    "endian", "shorewall", "firehol", "nftables", "iptables", "ufw", "csf",
    "fail2ban", "crowdsec", "suricata", "snort", "zeek", "bro", "securityonion",
    "wazuh", "ossec", "hids", "aide", "tripwire", "samhain", "osquery",
    "fleetdm", "kolide", "defender", "intune", "jamf", "airwatch",
    "mobileiron", "vmware", "workspace-one", "sccm", "mecm", "landesk",
    "ivanti", "manageengine", "desktop-central", "dameware", "teamviewer",
    "anydesk", "splashtop", "logmein", "gotomypc", "remotepc", "parsec",
    "rustdesk", "nomachine", "x2go", "xrdp", "freerdp", "remmina", "royalts",
    "mremote", "devolutions", "passwordstate", "passwordboss", "lastpass",
    "1password", "bitwarden", "dashlane", "keeper", "nordpass", "roboform",
    "stickypassword", "intuitive", "mypasswords", "passwordsafe", "keepass",
    "keepassxc", "pass", "secret-service", "gnome-keyring", "kwallet",
    "mac-keychain", "windows-credentials", "credential-manager", "hashicorp-vault",
    "cyberark", "conjur", "delinea", "thycotic", "secret-server", "beyondtrust",
    "pam", "privileged-access", "identity", "iam", "idm", "IGA", "access-mgmt",
    "okta", "onelogin", "pingidentity", "auth0", "keycloak", "fusionauth",
    "gluu", "shibboleth", "simplesamlphp", "cas", ".apereo", "moodle",
    "blackboard", "canvas", "d2l", "brightspace", "schoology", "powerschool",
    "infinite-campus", "tyler-sis", "skyward", "alma", "factsmgt", "renweb",
    "finalsite", "blackbaud", "ellucian", "banner", "colleague", "peoplesoft",
    "workday", "sap", "oracle", "netsuite", "sage-intacct", "quickbooks",
    "xero", "freshbooks", "wave", "freeagent", "kashoo", "zoho", "hubdoc",
    "expensify", "concur", "tripactions", "navan", "brex", "ramp", "bill",
    "melio", "plaid", "yodlee", "finicity", "mx", "akoya", "fiserv-data",
    "datashare", "dun-bradstreet", "equifax", "experian", "transunion",
    "lexisnexis", "acxiom", "live-ramp", "neustar", "oracle-data-cloud",
    "salesforce-dmp", "adobe-aam", "lotame", "krux", "bluekai", "nielsen",
    "comscore", "quantcast", "chartbeat", "parsely", "mixpanel", "amplitude",
    "heap", "segment", "mparticle", "tealium", "braze", "airship", "clevertap",
    "moengage", "onesignal", "pushwoosh", "urban-airship", "iterable",
    "customer-io", "klaviyo", "postscript", "attentive", "tapcart", "yotpo",
    "okendo", "judge-me", "loox", "stamped", "rivo", "smile-io", "loyaltylion",
    "swell", "yopto", "recharge", "ordergroove", "loop", "returns", "aftership",
    "shipstation", "shipbob", "shipmonk", "fulfillment", "ware2go", "redstag",
    "deliverr", "flexe", "flowspace", "stord", "fourkites", "project44",
    "macropoint", "descartes", "blujay", "eweinstein", "transporeon", "transplace",
    "loadsmart", "convoy", "uber-freight", "amazon-freight", "freightos",
    "zen Cargo", " Flexport", " Expeditors", "Kuehne+Nagel", "DB Schenker",
    "DSV", "GEODIS", "CEVA", "Panalpina", "Expeditors-e", "Nippon-Express",
    "Kerry-Logistics", "Sinotrans", "C.H. Robinson", "TQL", "Coyote",
    "XPO", "Schneider", "J.B. Hunt", "Landstar", "Werner", "Old Dominion",
    "YRC", "Estes", "R+L Carriers", "SAIA", "ABF", "FedEx", "UPS", "DHL",
    "USPS", "OnTrac", "LaserShip", "GSO", "Spee-Dee", "CanadaPost", "RoyalMail",
    "Hermes", "DPD", "GLS", "ParcelForce", "TNT", "PostNL", "LaPoste",
    "Colissimo", "Chronopost", "Correos", "Seur", "MRW", "DHL-Express",
    "DHL-Ecommerce", "Aramex", "AustraliaPost", "NZPost", "JapanPost",
    "KoreaPost", "ChinaPost", "SingPost", "ThaiPost", "IndiaPost", "BlueDart",
    "Delhivery", "Ekart", "Flipkart", "Amazon-IN", "Myntra", "Snapdeal",
    "Paytm-Mall", "ShopClues", "BigBasket", "Grofers", "Blinkit", "Zepto",
    "Dunzo", "Swiggy", "Zomato", "UberEats", "DoorDash", "Grubhub", "Postmates",
    "Instacart", "GoPuff", "Deliveroo", "JustEat", "Takeaway", "Foodpanda",
    "Delivery-Hero", "Wolt", "Glovo", "Rappi", "iFood", "PedidosYa", "Menulog",
    "SkipTheDishes", "Deliveroo-AU", "Uber-AU", "DiDi", "Ola", "Lyft", "Bolt",
    "Grab", "Gojek", "Careem", "Yandex", "Gett", "FREE NOW", "MyTaxi", "Cabify",
    "99", "Beat", "Pathao", "Bykea", "InDriver", "BlaBlaCar", "FlixBus",
    "Greyhound", "Megabus", "National-Express", "Ouigo", "Eurostar", "Thalys",
    "Trenitalia", "Renfe", "SNCF", "Deutsche-Bahn", "SBB", "OBB", "NS",
    "DSB", "SJ", "VR", "MTR", "SMRT", "KTM", "Indian-Railways", "Amtrak",
    "Via-Rail", "Greyhound-CA", "Translink", "TfL", "MTA", "NJTransit",
    "MBTA", "CTA", "WMATA", "BART", "Caltrain", "Metrolink", "TriMet",
    "King-County", "SoundTransit", "VIA", "STM", "BIXI", "Citi-Bike", "Divvy",
    "Capital-Bikeshare", "Bluebikes", "Metro-Bike", "Breeze", "Metro-Transit",
    "OC-Transpo", "TransLink", "GO-Transit", "Presto", "Opal", "Myki",
    "Oyster", "Navigo", "OV-Chipkaart", "Rejsekort", "SL-Access", "Travel-Card",
    "Clipper", "Ventra", "SmarTrip", "CharlieCard", "MetroCard", "T-Money",
    "Suica", "Pasmo", "Octopus", "Ez-Link", "Beep", "Tap-Go", "MoBib",
    "Leap", "Bfree", "Watcard", "U-Pass", "BuckID", "TigerCard", "HuskyCard",
    "Wiscard", "CUID", "OneCard", "CampusCard", "Student-ID", "Alumni",
    "Library", "catalog", "opac", "dspace", "fedora", "islandora", "samvera",
    "greenstone", "eprints", "open-journal-systems", "open-conference-systems",
    "open-monograph-press", "public-knowledge-project", "wordpress",
    "drupal", "joomla", "magento", "prestashop", "shopify", "bigcommerce",
    "woocommerce", "squarespace", "wix", "weebly", "godaddy", "bluehost",
    "hostgator", "siteground", "inmotion", "dreamhost", "a2hosting", "namecheap",
    "ovh", "hetzner", "digitalocean", "linode", "vultr", "upcloud", "scaleway",
    "aws-us-east", "aws-us-west", "aws-eu-west", "aws-eu-central", "aws-ap-south",
    "aws-ap-northeast", "aws-ap-southeast", "aws-sa-east", "aws-ca-central",
    "azure-eastus", "azure-westeurope", "azure-southeastasia", "gcp-us-central",
    "gcp-europe-west", "gcp-asia-east", "oracle-cloud", "ibm-cloud", "alibaba-cloud",
    "tencent-cloud", "huawei-cloud", "baidu-cloud", "jd-cloud", "ucloud",
    "qcloud", "kingsoft-cloud", "cloudsigma", "cloudcone", "ramnode", "buyvm",
    "frantech", "pterodactyl", "gamepanel", "multicraft", "tcadmin", "opengamepanel",
    "aurora", "unturned", "rust", "minecraft", "terraria", "starbound",
    "factorio", "satisfactory", "valheim", "ark", "conan", "7days", "project-zomboid",
    "dont-starve", "oxygen-not-included", "rimworld", "dwarf-fortress",
    "caves-of-qud", "brogue", "dcss", "nethack", "angband", "tomenet", "mangband",
    "angband-live", "sil-q", "poschengband", "composband", "frogcomposband",
    "elysium", "jelly", "slay-the-spire", "monster-train", "roguebook",
    "darkest-dungeon", "baldurs-gate", "planescape", "icewind-dale", "neverwinter",
    "nwn", "nwn2", "kotor", "kotor2", "dragon-age", "mass-effect", "me2", "me3",
    "andromeda", "anthem", "jade-empire", "swtor", "swg", "swgemu", "everquest",
    "eq2", "vanguard", "daoc", "uo", "wurm", "mortal-online", "darkfall", "albion",
    "eve-online", "black-desert", "archeage", "lineage", "lineage2", "aion",
    "tera", "blade-and-soul", "guild-wars", "gw2", "eso", "final-fantasy-xiv",
    "ff11", "ffxiv", "warframe", "destiny", "destiny2", "division", "division2",
    "ghost-recon", "rainbow-six", "r6s", "csgo", "cs2", "valorant", "overwatch",
    "ow2", "apex", "fortnite", "pubg", "escape-from-tarkov", "eft", "rust-game",
    "dayz", "arma", "squad", "hell-let-loose", "post-scriptum", "beyond-the-wire",
    "project-reality", "bf2", "bf3", "bf4", "bf1", "bf5", "bf2042", "cod",
    "cod2", "cod4", "mw", "mw2", "mw3", "blackops", "cold-war", "vanguard-cod",
    "warzone", "halo", "master-chief", "infinite", "gears-of-war", "titanfall",
    "titanfall2", "apex-legends", "left-4-dead", "l4d2", "back-4-blood", "killing-floor",
    "killing-floor2", "payday", "payday2", "payday3", "vermintide", "darktide",
    "deep-rock-galactic", "drg", "satisfactory-game", "factorio-game", "shapez",
    "mindustry", "barotrauma", "stationeers", "space-engineers", "empyrion",
    "star-citizen", "elite-dangerous", "no-mans-sky", "subnautica", "subnautica2",
    "the-forest", "sons-of-the-forest", "green-hell", "stranded-deep", "raft",
    "dont-starve-together", "dst", "oxygen-not-included", "oni", "rimworld-together",
    "civilization", "civ5", "civ6", "humankind", "old-world", "oldworld", "stellaris",
    "eu4", "hoi4", "vic3", "imperator", "ck2", "ck3", "total-war", "shogun", "rome",
    "attila", "thrones", "three-kingdoms", "troy", "warhammer", "warhammer2",
    "warhammer3", "gladius", "battlesector", "dawn-of-war", "dow2", "dow3",
    "company-of-heroes", "coh2", "coh3", "men-of-war", "gates-of-hell", "steel-division",
    "wargame", "warno", "regiments", "conflict-zones", "flashpoint", "operation-flashpoint",
    "arma-cold-war", "arma-reforger", "vbs", "vbs4", "tactical", "simulation-tactical",
    "milsim", "combat-mission", "close-combat", "theatre-of-war", "graviteam",
    "panzer-corps", "panzer-corps2", "unity-of-command", "commander-the-navy",
    "war-in-the-pacific", "witp", "war-in-the-east", "wite", "decisive-campaigns",
    "strategic-command", "shadow-empire", "star-ruler", "star-ruler2", "distant-worlds",
    "aurora-4x", "starsector", "fractured-space", "nebula", "endless-space",
    "endless-space2", "endless-legend", "humankind-game", "old-world-game",
    "age-of-wonders", "aow3", "aow4", "planetfall", "pandora", "civilization-beyond",
    "civ-beyond-earth", "sid-meier", "alpha-centauri", "colonization", "pirates",
    "railroad-tycoon", "simcity", "cities-skylines", "cities-xl", "cities-xxl",
    "surviving-mars", "surviving-the-aftermath", "frostpunk", "frostpunk2",
    "rimworld-ideology", "rimworld-royalty", "rimworld-biotech", "rimworld-anomaly",
    "dwarf-fortress-steam", "dungeon-fortress", "keeperrl", "warsim", "warsim-razdis",
    "kingdoms-and-castles", "kingdom-castles", "stronghold", "stronghold-crusader",
    "stronghold2", "stronghold-legends", "stronghold3", "firefly", "anno",
    "anno1404", "anno2070", "anno2205", "anno1800", "settlers", "settlers-online",
    "tropico", "tropico5", "tropico6", "tropico4", "tropico3", "rise-of-industry",
    "industry-giant", "transport-fever", "transport-fever2", "train-fever",
    "railroad-corporation", "rail-route", "rolling-line", "train-sim-world",
    "train-simulator", "trains", "railworks", "msts", "open-rails", "run8",
    "zusi", "trainz", "a-train", " Transport-Giant", "Traffic-Giant", "patrician",
    "port-royale", "patrician4", "rise-of-venice", "anno", "port-royale3",
    "port-royale4", "new-world", "the-patrician", "hanse", "lubek", "cogs",
    "grand-ages", "grand-ages-medieval", "grand-ages-rome", "imperium-romanum",
    "glory-of-the-roman-empire", "caesar", "caesar3", "caesar4", "pharaoh",
    "cleopatra", "zeus", "poseidon", "emperor", "children-of-the-nile", "immortal-cities",
    "nile-online", "townsmen", "the-settlers-online", "culture", "culture-northland",
    "culture-8th", "world-of-zellians", "space-colony", "startopia", "mafia",
    "mafia2", "mafia3", "mafia-definitive", "l.a.noire", "max-payne", "max-payne2",
    "max-payne3", "bully", "manhunt", "manhunt2", "the-warriors", "midnight-club",
    "midnight-club2", "midnight-club3", "midnight-club-la", "red-dead",
    "red-dead2", "red-dead-online", "gta", "gta2", "gta3", "gta-vc", "gta-sa",
    "gta4", "gta5", "gta-online", "gta6", "rockstar", "social-club", "launcher",
    "epic-games", "epic-games-store", "unreal-engine", "unreal-tournament",
    "ut2004", "ut3", "ut4", "paragon", "fortnite-creative", "fall-guys",
    "rocket-league", "rl", " among-us", "fall-guys-game", "gang-beasts",
    "human-fall-flat", "pummel-party", "overcooked", "overcooked2", "moving-out",
    "tools-up", "out-of-space", "spac-crew", "lovers-in-a-dangerous-spacetime",
    "nova-drift", "starbound-game", "terraria-game", "core-keeper", "dont-starve",
    "oxygen-not-included", "rimworld", "stardew-valley", "stardew", "harvest-moon",
    "story-of-seasons", "rune-factory", "my-time-at-portia", "my-time-at-sandrock",
    "spiritfarer", "wytchwood", "cozy-grove", "little-wood", "forager", "garden-story",
    "snacko", "paleo-pines", "shack-cactus", "alchemic-cutie", "staxel", "farm-together",
    "farm-sim", "farm-simulator", "farming-sim", "farming-simulator", "fs19",
    "fs22", "fs25", "pure-farming", "real-farm", "farm-manager", "cattle-and-crops",
    "farmonaut", "agroneer", "farmsim", "landwirtschafts-simulator", "john-deere",
    "case-ih", "new-holland", "fendt", "claas", "massey-ferguson", "kubota",
    "valtra", "deutz-fahr", "same", "lamborghini-tractors", "carraro", "antonio-carraro",
    "sdf", "same-deutz-fahr", "steiger", "versatile", "challenger", "mtx",
    "mccormick", "landini", "zetor", "ursus", "belarus", "rsm", "k-700", "k-700a",
    "k-701", "k-744", "k-9000", "k-9450", "k-9520", "k-9500", "k-9300", "k-9200",
    "k-9100", "k-9000", "k-7700", "k-7600", "k-7500", "k-7400", "k-7300",
    "k-7000", "k-6440", "k-6400", "k-6340", "k-6300", "k-6240", "k-6200",
    "k-6140", "k-6100", "k-6000", "k-5440", "k-5400", "k-5340", "k-5300",
    "k-5240", "k-5200", "k-5140", "k-5100", "k-5000", "k-4240", "k-4200",
    "k-4140", "k-4100", "k-4000", "k-3440", "k-3400", "k-3340", "k-3300",
    "k-3240", "k-3200", "k-3140", "k-3100", "k-3000", "k-2440", "k-2400",
    "k-2340", "k-2300", "k-2240", "k-2200", "k-2140", "k-2100", "k-2000",
    "k-1540", "k-1500", "k-1440", "k-1400", "k-1340", "k-1300", "k-1240",
    "k-1200", "k-1140", "k-1100", "k-1000", "k-944", "k-900", "k-844",
    "k-800", "k-744", "k-700", "k-644", "k-600", "k-544", "k-500", "k-444",
    "k-400", "k-344", "k-300", "k-244", "k-200", "k-144", "k-100", "k-90",
    "k-80", "k-70", "k-60", "k-50", "k-40", "k-30", "k-20", "k-10", "k-7",
    "k-5", "k-3", "k-1", "k-0", "m-9000", "m-8000", "m-7000", "m-6000",
    "m-5000", "m-4000", "m-3000", "m-2000", "m-1000", "m-900", "m-800",
    "m-700", "m-600", "m-500", "m-400", "m-300", "m-200", "m-100", "m-90",
    "m-80", "m-70", "m-60", "m-50", "m-40", "m-30", "m-20", "m-10", "m-1",
    "t-9000", "t-8000", "t-7000", "t-6000", "t-5000", "t-4000", "t-3000",
    "t-2000", "t-1000", "t-900", "t-800", "t-700", "t-600", "t-500", "t-400",
    "t-300", "t-200", "t-100", "t-90", "t-80", "t-70", "t-60", "t-50", "t-40",
    "t-30", "t-20", "t-10", "t-1", "x-9000", "x-8000", "x-7000", "x-6000",
    "x-5000", "x-4000", "x-3000", "x-2000", "x-1000", "x-900", "x-800",
    "x-700", "x-600", "x-500", "x-400", "x-300", "x-200", "x-100", "x-90",
    "x-80", "x-70", "x-60", "x-50", "x-40", "x-30", "x-20", "x-10", "x-1",
    "y-9000", "y-8000", "y-7000", "y-6000", "y-5000", "y-4000", "y-3000",
    "y-2000", "y-1000", "y-900", "y-800", "y-700", "y-600", "y-500", "y-400",
    "y-300", "y-200", "y-100", "y-90", "y-80", "y-70", "y-60", "y-50", "y-40",
    "y-30", "y-20", "y-10", "y-1", "z-9000", "z-8000", "z-7000", "z-6000",
    "z-5000", "z-4000", "z-3000", "z-2000", "z-1000", "z-900", "z-800",
    "z-700", "z-600", "z-500", "z-400", "z-300", "z-200", "z-100", "z-90",
    "z-80", "z-70", "z-60", "z-50", "z-40", "z-30", "z-20", "z-10", "z-1",
    "vault-47", "vault-48", "vault-49", "vault-50",
]

# Убедимся, что секретный сабдомен есть в списке
if SECRET_SUBDOMAIN not in SUBDOMAINS:
    SUBDOMAINS.append(SECRET_SUBDOMAIN)

# Шаблоны для разных сабдоменов
NOISE_TEMPLATES = {
    "www": "Welcome to MegaCorp public homepage.",
    "mail": "Webmail login page.",
    "ftp": "FTP service directory listing.",
    "admin": "Admin panel. Access denied.",
    "api": "{\"version\":\"1.0\",\"status\":\"ok\"}",
    "dev": "Development environment. Coming soon.",
    "test": "QA test server. Nothing interesting.",
    "staging": "Staging environment. Authorized only.",
    "prod": "Production monitoring dashboard.",
    "blog": "MegaCorp blog - latest posts.",
    "news": "No news today.",
    "support": "Support ticket system.",
    "help": "Help center.",
    "docs": "API documentation.",
    "portal": "Employee portal login.",
    "intranet": "Internal network. 403.",
    "vpn": "VPN gateway.",
    "git": "Git repository list.",
    "gitlab": "GitLab instance.",
    "jenkins": "Jenkins CI/CD.",
    "docker": "Docker registry.",
    "kube": "Kubernetes dashboard.",
    "monitor": "Grafana dashboard.",
    "logs": "Log aggregator.",
    "backup": "Backup server.",
    "db": "Database management UI.",
    "cache": "Redis cache status.",
    "cdn": "Content delivery network.",
    "static": "Static assets.",
    "media": "Media server.",
    "images": "Image gallery.",
    "video": "Video streaming service.",
    "stream": "Live stream.",
    "events": "Events calendar.",
    "calendar": "Company calendar.",
    "meet": "Video conferencing.",
    "office": "Office 365 redirect.",
    "teams": "Teams collaboration.",
    "share": "SharePoint portal.",
    "drive": "Cloud drive.",
    "files": "File storage.",
    "upload": "Upload service.",
    "download": "Download portal.",
    "update": "Update server.",
    "upgrade": "Upgrade portal.",
    "patch": "Patch management.",
    "security": "Security operations.",
    "siem": "SIEM dashboard.",
    "soc": "SOC monitoring.",
    "waf": "Web application firewall.",
    "firewall": "Firewall management.",
    "gateway": "Gateway configuration.",
    "proxy": "Proxy server.",
    "secrets": "Secret management service.",
    "kms": "Key management service.",
    "keys": "Key server.",
    "crypto": "Crypto services.",
    "wallet": "Wallet service.",
    "blockchain": "Blockchain node.",
    "nft": "NFT marketplace.",
    "defi": "DeFi protocol.",
    "trading": "Trading platform.",
    "exchange-rate": "Exchange rates.",
    "auth": "Authentication service.",
    "sso": "Single sign-on.",
    "login": "Login portal.",
    "register": "Registration page.",
    "oauth": "OAuth server.",
    "oidc": "OpenID Connect.",
    "saml": "SAML provider.",
    "ldap": "LDAP directory.",
    "ad": "Active Directory.",
    "directory": "Directory service.",
    "pki": "Public key infrastructure.",
    "ca": "Certificate authority.",
    "vault": "HashiCorp Vault.",
    "api-v1": "API v1 legacy.",
    "api-v2": "API v2 current.",
    "api-v3": "API v3 beta.",
    "graphql": "GraphQL endpoint.",
    "rest": "REST API.",
    "rpc": "RPC gateway.",
    "grpc": "gRPC service.",
    "websocket": "WebSocket server.",
    "realtime": "Realtime updates.",
    "analytics": "Analytics dashboard.",
    "bi": "Business intelligence.",
    "data": "Data portal.",
    "warehouse": "Data warehouse.",
    "ml": "Machine learning platform.",
    "ai": "AI services.",
    "model": "Model registry.",
    "training": "Training cluster.",
    "inference": "Inference endpoint.",
    "nlp": "NLP service.",
    "vision": "Computer vision.",
    "bot": "Bot service.",
    "agent": "Agent platform.",
    "assistant": "Virtual assistant.",
    "automation": "Automation server.",
    "workflow": "Workflow engine.",
    "scraper": "Web scraper.",
    "crawler": "Web crawler.",
    "indexer": "Search indexer.",
    "feed": "RSS feed.",
    "sitemap": "XML sitemap.",
    "robots": "robots.txt.",
    "ads": "Ad server.",
    "tracking": "Tracking pixel.",
    "pixel": "Conversion pixel.",
    "survey": "Survey tool.",
    "feedback": "Feedback form.",
    "reviews": "Reviews page.",
    "form": "Form builder.",
    "template": "Template library.",
    "faq": "FAQ page.",
    "kb": "Knowledge base.",
    "knowledge-base": "Knowledge base.",
    "help-center": "Help center.",
    "community": "Community forum.",
    "discussions": "Discussions.",
    "answers": "Q\u0026A.",
    "questions": "Questions.",
    "consulting": "Consulting services.",
    "services": "Services portal.",
    "solutions": "Solutions catalog.",
    "enterprise": "Enterprise portal.",
    "education": "Education portal.",
    "finance": "Finance portal.",
    "fintech": "Fintech services.",
    "healthcare": "Healthcare portal.",
    "retail": "Retail portal.",
    "ecommerce": "E-commerce platform.",
    "marketplace": "Marketplace.",
    "directory": "Business directory.",
    "listings": "Listings.",
    "comparison": "Price comparison.",
    "price": "Price list.",
    "deal": "Deals page.",
    "coupon": "Coupons.",
    "promo": "Promotions.",
    "discount": "Discounts.",
    "loyalty": "Loyalty program.",
    "rewards": "Rewards program.",
    "membership": "Membership portal.",
    "subscription": "Subscription management.",
    "billing-portal": "Billing portal.",
    "payment-portal": "Payment portal.",
    "invoice-portal": "Invoice portal.",
    "tax": "Tax portal.",
    "accounting": "Accounting system.",
    "payroll": "Payroll system.",
    "expenses": "Expense reports.",
    "budget": "Budget planning.",
    "forecast": "Forecasting.",
    "recruitment": "Recruitment portal.",
    "onboarding": "Onboarding portal.",
    "performance": "Performance reviews.",
    "wellness": "Wellness program.",
    "benefits": "Benefits portal.",
    "risk": "Risk management.",
    "audit": "Audit portal.",
    "compliance-training": "Compliance training.",
    "policy-portal": "Policy portal.",
    "gdpr-portal": "GDPR portal.",
    "consent": "Consent management.",
    "retention": "Data retention.",
    "backup-portal": "Backup portal.",
    "disaster-recovery": "DR portal.",
    "incident-response": "Incident response.",
    "threat": "Threat intelligence.",
    "vulnerability": "Vulnerability management.",
    "pentest": "Penetration testing.",
    "redteam": "Red team.",
    "blueteam": "Blue team.",
    "ctf": "CTF platform.",
    "bugbounty": "Bug bounty program.",
    "security-awareness": "Security awareness.",
    "phishing": "Phishing simulation.",
    "osint": "OSINT platform.",
    "threat-intel": "Threat intelligence.",
    "malware": "Malware analysis.",
    "forensics": "DFIR lab.",
    "investigation": "Investigation portal.",
    "case": "Case management.",
    "ticketing": "Ticketing system.",
    "cmdb": "CMDB.",
    "inventory": "Inventory.",
    "iot": "IoT platform.",
    "device": "Device management.",
    "sensor": "Sensor network.",
    "gateway-iot": "IoT gateway.",
    "digital-twin": "Digital twin.",
    "visualization": "Data visualization.",
    "3d": "3D viewer.",
    "ar": "AR portal.",
    "vr": "VR portal.",
    "metaverse": "Metaverse.",
    "smart-contract": "Smart contract platform.",
    "ipfs": "IPFS gateway.",
    "matrix": "Matrix server.",
    "xmpp": "XMPP server.",
    "irc": "IRC server.",
    "tor": "Tor gateway.",
    "ens": "ENS resolver.",
    "bitcoin": "Bitcoin node.",
    "ethereum": "Ethereum node.",
    "solana": "Solana node.",
    "polkadot": "Polkadot node.",
    "kubernetes": "K8s API.",
    "prometheus": "Prometheus.",
    "grafana": "Grafana.",
    "kibana": "Kibana.",
    "jaeger": "Jaeger.",
    "airflow": "Airflow.",
    "spark": "Spark UI.",
    "jupyter": "JupyterHub.",
    "notebook": "Notebooks.",
    "github": "GitHub Enterprise.",
    "confluence": "Confluence.",
    "jira": "Jira.",
    "zendesk": "Zendesk.",
    "salesforce": "Salesforce.",
    "hubspot": "HubSpot.",
    "stripe": "Stripe dashboard.",
    "paypal": "PayPal portal.",
    "google": "Google Workspace.",
    "slack": "Slack.",
    "zoom": "Zoom.",
    "teams": "Teams.",
    "dropbox": "Dropbox.",
    "box": "Box.",
    "onedrive": "OneDrive.",
}

def page_for(sub: str) -> str:
    if sub == SECRET_SUBDOMAIN:
        return f"Welcome to the secret vault.\nYour flag: {FLAG}"
    if sub in NOISE_TEMPLATES:
        return NOISE_TEMPLATES[sub]
    return f"Subdomain '{sub}.{DOMAIN}' is reserved for future use."

@app.route("/", defaults={"path": ""})
@app.route("/<path:path>")
def catch_all(path):
    host = request.headers.get("Host", "")
    # Может быть target:5000 или subdomain.megacorp.local
    sub = host.split(".")[0].split(":")[0].lower()
    if sub == DOMAIN or sub == "":
        sub = "www"
    body = page_for(sub)
    return render_template_string("<pre>{{ body }}</pre>", body=body), (200 if sub == SECRET_SUBDOMAIN else 404)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
